# In this section:

# 1. Create a user model using devise generators.
# 2. Secure the home page of our app with devise.
# 3. Run our app and sign-up.
# 4. Add a link to sign-out.

# 1. Create a User model using the Devise generator. This will give us a Rails model with extra authentication methods and attributes needed for Devise,

	rails generate devise user
	
	
# 1.1 Take a look at what it's created:

   # invoke  active_record
   #   create    db/migrate/20120629090415_devise_create_users.rb
   #   create    app/models/user.rb
   #   invoke    rspec
   #   create      spec/models/user_spec.rb
   #   insert    app/models/user.rb
   #   route  devise_for :users
   
# We have our first database migration db/migrate{timestamp}_devise_create_users.rb, a user model app/models/user.rb and a file for writing tests for our user spec/app/models/user.rb

# 1.2 Our first migration

# Take a look at the migration in db/migrate and you'll see some ruby code for creating the user model Devis has generated.
# Note that the table name is plural users for a singular model user.
# Lets run the migration and it will create the table in our database:

  bundle exec rake db:migrate
  
# you should see some sql statements appear in the console as the migration creates the users table. 


# 2. Now let's secure the home page with Devise:

	before_filter :authenticate_user!
	
# 3 Let's include the recommendations from the Devise notice:

#in app/views/layouts/application.html.erb

<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

# 'notice' and 'alert' are two helper methods that use the Rails flash messaging. Flash is an easy way of sending messages generated
# in our controllers to the user. For example the statment flash[:notice]	= "You're logged in" somewhere oin a controller will 
# appear in the notice method above
	

# 4. Run the app and Sign up

# 5. Create the logout link in application.html.erb

<% if user_signed_in? %>
   <div><%= link_to "sign-out", destroy_user_session_path, :method => :delete  %></div>
<% end %>

# user_signed_in? is a helper method generated by devise, link_to is a Rails helper for generating html links. 
# In this case we're generating a link with text 'sign-out' and a url generated by the devise route 
# destroy_user_session_path. We'll cover routes a bit more in the next section. 